type UserReport = {
    idRelato: number,
    latitude: number,
    longitude: number,
    endereco: string,
    criadoQuando: Date,
    descricaoRelato: string,
    titulo: string,
    nomeCategoria: string,
    descricaoCategoria: string,
    idCategoria: number,
    nomeUser: string,
    emailUser: string,
    quantLike: number,
    quantDeslike: number,
}
